name: Render README

on:
  schedule:
    # Every Sunday at midnight UTC
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      
      - name: Render README.qmd
        run: quarto render README.qmd
      
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff --staged --quiet || (git commit -m "Update README" && git push)